### ISSUE TITLE
Role Model Video Suggestions

### ISSUE THREAD

**Issue by wolfkin** [kelukelugames/kelukelugames.github.io#1]
so I'll do what I can to drop suggestions here before I've decided on them and made them ready for formatting

**Comment by wolfkin** [comment]
"We Need Male Role Models"

> Panelist Kevin Cobbin of Cobbin Legal shares his thoughts on role models during the E3 Focus Forum - Absentee Fathers held 10-17-09 by the E3 Business Group. The forum was in response to the community of Jacksonville, FL's request for more dialogue on absentee fathers and other issues related to preventing infant mortality as discussed during the historic Real Talk... Real Change event in July 2009.
> 
> Kevin Cobbin is the principal of Cobbin Legal and practices family law. He is an fast riser in the legal community and a valuable resource to E3 members. Contact Kevin at kmcobbin@cobbinlegal.com

https://www.youtube.com/watch?v=vMUwTJFQt3Q

**Comment by kelukelugames** [comment]
Thanks for submitting the video! The talk is interesting, but I'm not sure if Kevin is famous enough for most people to recognize him.
